from __future__ import annotations
from typing import Protocol, AsyncIterator, Dict, Any

class DataFeed(Protocol):
    async def start(self, symbols: list[str]) -> None: ...
    async def stop(self) -> None: ...
    def __aiter__(self) -> AsyncIterator[Dict[str, Any]]: ...
    async def __anext__(self) -> Dict[str, Any]: ...

class StrategyBase(Protocol):
    async def on_start(self, config: dict) -> None: ...
    async def on_tick(self, tick: dict) -> dict: ...
    async def on_stop(self) -> None: ...